### ISSUE TITLE
Too much power consumption of  the remote in sleep mode

### ISSUE THREAD

**Issue by drykov** [p1rse/robot-sumo-start-module#1]
When power up the remote consumes appropriate 0.4uA at 3v.
After the first press of any button it tries to go to sleep, but the current consumption keeps at relatively high 180uA.
It happens because after measuring of the battery voltage the ADC is left in enabled state.
Probably it could be fixed by disabling ADC by adding
	ADCSRA &= ~_BV(ADEN); // disable ADC after measurement to stop draining power
at line 279 in main.c file.

**Comment by p1rse** [comment]
Hi Drykov.
This sounds like a great improvement!
I have noticed that the remote seem to deplete batteries a bit faster than desired.
Are you able to program a remote and verify it?
Best Regards

**Comment by drykov** [comment]
I tried a proposed fix and it seems good. I put updated sources and the hex built with Atmel Studio 7 at https://github.com/drykov/robot-sumo-start-module (master for your master and InfiniteStart branch for repetition settings used in the originally published hex) for our robotics team.
Unfortunately I'm not an expert in AVR so you have to verify it on you own.

**Comment by p1rse** [comment]
I have verified the fix and it is now merged, god job Drykov!
