### ISSUE TITLE
New hex does not turn on IR programming LED

### ISSUE THREAD

**Issue by andreikovari** [p1rse/robot-sumo-start-module#3]
I've made a pair of custom remotes and when I tried to upload the last pushed hex, the programming LED does not flicker. The start/stop ones flicker, but I can't check it on a module, since I can't program it to the new address. The fuse bits are E2D7FF
I'll try to use the oscilloscope to check the output on the start/stop LEDs

**Comment by p1rse** [comment]
If you checkout the previous version of the hex file (1.0) instead of new version (1.01), are you then able to program?

**Comment by andreikovari** [comment]
I've uploaded the 1.0, still nothing. Checked with the oscilloscope, no output on the programming LED

**Comment by andreikovari** [comment]
Also, I forgot to mention that the visible LEDs seem to work ok

**Comment by p1rse** [comment]
Hi, it sounds like there is some HW issue in your custom remote since the 1.0 for sure works on the existing remotes.

**Comment by andreikovari** [comment]
The hardware is the same (schematic wise). I have an older version that worked, but I lost the old hex.
Now, the new code, does not work. Neither on the previous version or the new one.
Could it be a compiling or fusebits issue?

**Comment by andreikovari** [comment]
Could it be that I can't compile it using atmega168pa option, and I have selected instead atmega168p?
"unknown MCU 'atmega168pa' specified"

**Comment by andreikovari** [comment]
This issue is solved. 
The dipswitches I use had a default off state when were shipped (and also masked with a capton tape for reflow soldering). And since I wanted to give them to the user "untouched" I never removed the tape or changed the dipswitches.
And my guess (I'll look into the code too) is that with all the dipswitches turned off, it can't select an address, so the programming LED does not flicker.

**Comment by p1rse** [comment]
Ah good that you found the root cause. ID 0 and 1 is reserved so that is probably the issue. In ID 0 the referee remote work as a TV remote to test the home mode. You can see more details here https://p1r.se/startmodule/for-organizers/referees-remote/

**Comment by andreikovari** [comment]
So, I've tested with various versions of the code, they all work. The dipswitches caused the problem.
The issue can be closed. Thank you for all the support!
