### ISSUE TITLE
Prebuilt module makefile F_CPU wrong

### ISSUE THREAD

**Issue by Eryk-Mozdzen** [p1rse/robot-sumo-start-module#4]
Hi,
in prebuilt module makefile the default F_CPU value is wrong.

ATtiny13A can't work on internal 8MHz oscillator because it does not exist (4,8MHz, 9.6MHz or 128 kHz available).
With the proposed fuse bits configuration only changing from CLOCK=8000000 to CLOCK=4800000 made this module work.

I want to put this here because it takes me few hours of debugging my hardware to find what is the issue.

**Comment by p1rse** [comment]
Hello Eryk
Thanks you for the input! 
I have corrected the file.
Best Regards
